sass:
    sass_dir: assets/bootstrap/scss

plugins:
  - jekyll-get-json

jekyll_get_json:
  - data: episodes
    json: 'https://feed2json.org/convert?url=https%3A%2F%2Ffeeds.buzzsprout.com%2F1341670.rss'

url: "https://pglevy.github.io/mm4t/"
