sass:
    sass_dir: assets/bootstrap/scss

plugins:
  - jekyll-get-json

jekyll_get_json:
  - data: episodes
    json: 'feed.json'

#live
url: "https://www.moneymovesforteens.com"
baseurl: "/"

#local
# baseurl: /mm4t-site

permalink: /:categories/:year/:month/:day/:title:output_ext

title: Money Moves for Teens Podcast
