- name: Apple Podcasts
  url: "https://podcasts.apple.com/us/podcast/money-moves-for-teens/id1513765051"

- name: Spotify
  url: "https://open.spotify.com/show/73hQ29j396y2cYs77bnXGr"

- name: Google Podcasts
  url: "https://podcasts.google.com/?feed=aHR0cHM6Ly9mZWVkcy5zb3VuZGNsb3VkLmNvbS91c2Vycy9zb3VuZGNsb3VkOnVzZXJzOjQ5MjUxMDM1NC9zb3VuZHMucnNz&ved=0CAIQ7dUFahcKEwjQ7YGB1cfpAhUAAAAAHQAAAAAQFA"

- name: More Options
  url: "https://archive.org/details/money-moves-for-teens-podcast/"
